

version: '3.8'

services:

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=720h'
      # allow hot-reload of config
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor
    restart: unless-stopped

  grafana:
    build: './grafana'
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped

  # Local container-wise metrics
  # https://medium.com/@bhargavshah2011/monitoring-docker-containers-using-cadvisor-and-prometheus-5350ae038f45
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    privileged: true
    # Enable to expose these metrics directly and externally
    # ports:
    #   - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

volumes:
  prometheus_data: {}