
# config file version
apiVersion: 1

datasources:
- name: prometheus
  isDefault: true
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  editable: false
- name: InfluxDB
  type: influxdb
  access: proxy
  database: auto_trader
  url: http://172.17.0.1:8086
  jsonData:
    httpMode: GET
